Replaced SHA with name
cirrus-actions/discord pull request #16
Opened 2019-02-15 14:52 UTC by RDIL

2019-02-15 15:34 UTC, fkorotkov commented on hooks.sh
> +
Don't you need to wrap it in `$(...)`? Have you tested it?

2019-02-15 15:35 UTC, RDIL commented on hooks.sh
> +
Still at school, Discord blocked.  Do you mind testing it? (sorry)

2019-02-15 15:43 UTC, fkorotkov commented on hooks.sh
> +
Wasn't able to. Seems I need my own discord server to be able to create a webhook and so on? Wasn't ready for the effort. 😅  

It can wait though.

2019-02-15 15:45 UTC, RDIL commented on hooks.sh
> +
Oops, forgot to give you permissions.  The existing one is `https://discordapp.com/api/webhooks/544638663804452884/DIe1B7nDKtUFWiVbiTkPoJebOjv1YymMLOLPuZPvqsicP8W8nk_Ltp-ezGF-37_XRaEv` if you need it.  I get home at 4PM so I can test it then.

2019-02-18 19:32 UTC, fkorotkov approved these changes

2019-02-18 20:29 UTC, RDIL commented
Says the commit was null in my testing.

2019-02-18 20:46 UTC, fkorotkov requested changes

2019-02-18 20:46 UTC, fkorotkov commented on hooks.sh
> +COMMIT=$(jq -r ".check_suite.head_commin.message" "$GITHUB_EVENT_PATH")
typo `s/commin/commit/`

2019-09-26 01:37 UTC, closed without merging